services:
    oxidcommunity.securitybundle.security.jwt.authenticator:
        class: OxidCommunity\SecurityBundle\Security\Jwt\Authenticator
        public: true

    oxidcommunity.securitybundle.security.jwt.provider:
        class: OxidCommunity\SecurityBundle\Security\Jwt\UserProvider


   
    oxidcommunity.securitybundle.security.webservice.authenticator:
        class: OxidCommunity\SecurityBundle\Security\Token\Authenticator
        public: true

    oxidcommunity.securitybundle.security.webservice.provider:
        class: OxidCommunity\SecurityBundle\Security\Token\UserProvider


    oxidcommunity.securitybundle.security.http.authenticator:
        class: OxidCommunity\SecurityBundle\Security\Http\Authenticator
        public: true
        arguments:
            - "@service_container"
        
    oxidcommunity.securitybundle.security.http.provider:
        class: OxidCommunity\SecurityBundle\Security\Http\UserProvider
        
    oxidcommunity.securitybundle.request_matcher:
        class: OxidCommunity\SecurityBundle\Security\RequestMatcher
        arguments:
            - "@router"